import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar";
import Profile from "@/components/shared/profile";
import { AnimatePresence } from "framer-motion";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} antialiased`}>
                <AnimatePresence>
                    <div className="sm:flex h-screen">
                        <Navbar />
                        <div className="flex-1 overflow-y-auto">
                            <div className="p-4 flex flex-col gap-4">{children}</div>
                        </div>
                    </div>
                </AnimatePresence>
            </body>
        </html>
    );
}
